### PR TITLE
Add XLStyle support

### PR DESCRIPTION
**Pull request by gvollant**
This PR add XLStyle 
It contain the original work from https://github.com/troldal/OpenXLSX/issues/104 CEXT
see https://github.com/troldal/OpenXLSX/issues/104

### CODE REVIEW

**Comment by gvollant** [comment]
thank you @CEXT-Dan for writing this code

**Comment by gvollant** [comment]
@troldal I've juste made a rebase against master after 0.3.2 release

**Comment by gvollant** [comment]
@troldal I made rebase against master

**Comment by gvollant** [comment]
@troldal what is your idea about this PR?

**Comment by gvollant** [comment]
There is a function xlsx_formatter
in this other library :
https://github.com/damian-m-g/xlsx_drone/blob/master/src/xlsx_drone.c

**Comment by gvollant** [comment]
@damian-m-g , is it a problem for you importing your xlsx_formatter which parse format to "understand" if it is a date on openxlsx ?

**Comment by CEXT-Dan** [comment]
Hi 

I’ve done some work on date-time and started on Fonts read only. It’s not done yet though.
I added a class OpenXLSX::XLNumberFormat which does a better job at detecting Currency, Percent and Date formatted numbers. (cell.style().numberFormat())

Anyway, you can get the custom format strings from cell.style().formatString() 
From there one can parse it I.e.  [$-10464]dddd\,\ mmmm\ d\,\ yyyy;

I wrote a parser for my app, not public because it requires non-standard formatting, it wasn’t hard, the only thing weird is excel uses mmmm for month instead of MMMM, so you have to take care when there’s minutes 

So kDate  Format string = m/d/yy\ h:mm;@ gets weird.

I’m a newb at GIT, so created a branch, so I don’t ruin things, which I’m quite good at.
https://github.com/CEXT-Dan/OpenXLSX/tree/feature/Detect_DateTime

I plan on doing a read only border class.

**Comment by gvollant** [comment]
Hello,
I suggest you create yourself a pull request after reducing the number of commit
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by gvollant** [comment]
@troldal @CEXT-Dan I rebased my gvollant:feature/XLStyle branch of this request with all modification from Cext_dan (merged in one commit) 
I've also added a fix for https://github.com/troldal/OpenXLSX/issues/133
You can both commit on my fork

**Comment by damian-m-g** [comment]
> @damian-m-g , is it a problem for you importing your xlsx_formatter which parse format to "understand" if it is a date on openxlsx ?

@gvollant feel free to import my code where it's neccessary. Sadly I'm unavailable to take a look at this issue during these days.

**Comment by gvollant** [comment]
@damian-m-g I've added code from xlsx_drone on commit https://github.com/troldal/OpenXLSX/pull/111/commits/bd152d289fae74ec0bbe1406a08e10099cffe6f3

@CEXT-Dan your feedback is welcome.
We probably need a 'cache' to avoid parsing each style at each cell...

You call all three add commit on my fork

**Comment by gvollant** [comment]
@troldal are you interrested by this feature?

**Comment by troldal** [comment]
@gvollant yes, I am indeed. I will eventually get around to it, but I have some other stuff I need to clean up before I proceed. But rest assured, I have not forgotten your PR.

**Comment by aral-matrix** [comment]
@gvollant - fyi - I have an implementation with nearly complete XLStyles support in my dev branch on codeberg - would you like to test it & give me feedback on what functionality might be missing?

The implementation is done in a separate XLStyles class, which allows manipulation of all workbook styles, and then the XLCell, XLRow and XLColumn classes have format getter / setter functions.

Please let me know here if interested.

**Comment by aral-matrix** [comment]
@gvollant  I just pushed my development branch - could you check that out / specifically Demo10 & see if there's still something missing you need?

**Comment by gvollant** [comment]
This is old and I don't remember well all those things...

**Comment by aral-matrix** [comment]
Fair enough, if you don't need it anymore - is it okay if I close the pull request as "superseded" with styles functionality in "testing" (in the development-aral branch)?
My implementation is so different from yours that I don't see much potential for a merge here, unfortunately.

**Pull request closed without merging**
