### PR TITLE
Handle pragma GCC warnings when compiling with MSVC

### PR DESCRIPTION
**Pull request by arnabanimesh**
When compiling with MSVC lots of pragma GCC warning pops up. This PR aims to fix that.

### CODE REVIEW

**Comment by aral-matrix** [comment]
Hey @arnabanimesh, thanks for your suggestion. However, this patch does not really make sense in the context of OpenXLSX, because the version you added a check for (```__GNUC__ >= 5```) is implied in that OpenXLSX does not support older standards than C++17.
Taken from https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017 

> **C++ 2017**
> [..]
> GCC 9.1 was the first release with non-experimental C++17 support, so the API and ABI of features added in C++17 is only stable since that release.

So anything below __GCC__ == 9 would not be able to compile OpenXLSX anyways.

**Comment by arnabanimesh** [comment]
@aral-matrix how does it look now?

I am only trying to check for the `__GNUC__` macro. The version is irrelevant.

Overall, this patch is necessary though. Otherwise MSVC is throwing many unnecessary warnings due to the pragma GCC preprocessor statements.

**Comment by aral-matrix** [comment]
Give me a few days to get back into my work from vacation time & I'll think about it - I have to check which check was introduced when - I have a feeling the solution is must simpler because the ```-Wunknown-pragmas``` warning may no longer be an issue for gcc, since the ```#ifdef _MSC_VER``` is there.

So I might just remove the lines that I originally introduced to suppress the same kind of warnings you get now, but on GCC.

**Comment by arnabanimesh** [comment]
@aral-matrix sure. no problem. Check the latest commit. It should be fine in my opinion.

**Comment by aral-matrix** [comment]
When I said "give me a few days" I didn't mean to update your commit :) I am fine with accepting smaller, localized changes, but when I have to review a pull request that does a broad edit across most source files, it's more work to review the pull request than to implement the change myself.
As I said, I'll have a look and then potentially just remove those lines directly in the code base.

**Comment by arnabanimesh** [comment]
I understood your comment earlier. I was free. So I simply did it anyways. 😃

I tested using both MSVC 14.39 and GCC 13.2. The code ran fine.

**Comment by aral-matrix** [comment]
Okay, I have updated the codebase to eliminate those warnings - I removed the obsolete "ignore unknown warnings" pragmas for GCC. 36640389bacffc9916a7903bd49f2b0165513d73
Please let me know if this does *not* fix all your warnings.

**Comment by arnabanimesh** [comment]
It is working fine. Thanks. :)

**Pull request closed without merging**
