### PR TITLE
Fixed compile errors in clang for XLStyles.hpp

### PR DESCRIPTION
**Pull request by MoniqueRFC**
Clang threw an error in two lines when compiling XLStyles.hpp because of assigning default. Changed assignment to delete.

### CODE REVIEW

**Comment by aral-matrix** [comment]
While I appreciate info about such issues, I can not merge a pull request that reformats ~ 300 lines. If you would like to propose a trivial fix, please do so in an issue report or in a pull request that contains *only* that fix, and nothing else.

Furthermore, could you please provide the exact error messages you get from clang on compiling?

**Comment by aral-matrix** [comment]
That doesn't help at all. Now there are two commits with ~300 changed lines. I think instead of trying to prepare a pull request, it would be better if you create an issue, explaining what's happening and 
> Furthermore, could you please provide the exact error messages you get from clang on compiling?

**Comment by MoniqueRFC** [comment]
Sorry about that, I thought I had disabled the auto-formatting in VSCode but it seems to still prevail. Okay, I will create an issue instead and post the compile error message.

**Comment by aral-matrix** [comment]
Resolved as per #310

**Pull request closed without merging**
